#!/bin/bash
# ref. https://github.com/pipelinedb/pipelinedb/blob/0.8.1/pkg/docker/scripts/startpipeline

set -e

# check if the data directory already exists
# if not, create it
if [ ! -d "/mnt/pipelinedb/data" ]; then
    mkdir -p /mnt/pipelinedb
    chmod 777 /mnt/pipelinedb
    su - pipeline -c "/usr/lib/pipelinedb/bin/pipeline-basebackup -X stream -D /mnt/pipelinedb/data -h pipelinedb -p 5432 -U replicator"
    cp /scripts/conf/*.conf /mnt/pipelinedb/data/
fi

su - pipeline -c "pipeline-server -D /mnt/pipelinedb/data"
