pipelinedb:
  build: ./pipelinedb
  ports:
    - "5432:5432"

fluentd:
  build: ./fluentd
  ports:
    - "24224:24224"
  links:
    - "pipelinedb"

nginx:
  build: ./nginx
  ports:
    - "80:80"
  log_driver: fluentd
  log_opt:
    fluentd-address: "localhost:24224"
    fluentd-tag: "docker.{{.ID}}"
